### ISSUE TITLE
[Bug] 设置公开访问的接口还是提示 401 未授权

### ISSUE THREAD

**Issue by geekyouth** [isxcode/flink-yun#135]
### Branch name (分支名)

main

### Bug description (缺陷描述)

![image](https://github.com/user-attachments/assets/f0895e80-aa00-4085-8ec9-81a930acb045)

**Comment by geekyouth** [comment]
改成 自定义请求头验证，还是 401 报错啊

![image](https://github.com/user-attachments/assets/2cc13682-9ce1-4ecd-a02f-ede486cbd774)
![image](https://github.com/user-attachments/assets/76789c7c-bf14-4cd1-a9da-823fbcd13faf)

**Comment by ispong** [comment]
访问地址不对

**Comment by geekyouth** [comment]
![image](https://github.com/user-attachments/assets/6ec22660-8140-44b1-9305-67d464db9fce)

这个格式在 HTTP 协议中表示从服务器的根路径开始访问，所以应该加上指定前缀
